stages:
  - build
  - test
  - deploy_test
  - deploy_pro

build:
  stage: build
  only:
    - dev
    - master
  script:
    - echo "build"
    - cp -rf src/* /data/

test:
  stage: test
  only:
    - dev
  script:
    - echo "test"
    - sh /data/sbin/stopall.sh

deploy_test:
  stage: deploy_test
  only:
    - dev
  script:
    - echo "deploy_test"
    - sh /data/sbin/startall.sh

deploy_pro:
  stage: deploy_pro
  only:
    - master
  script:
    - echo "deploy_pro"